[build]
builder = "poetry"
buildCommand = "poetry install --no-dev --no-interaction --no-ansi"

[deploy]
startCommand = "poetry run python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 